### ISSUE TITLE
GLES2 engine doesn't start @ 16bpp

### ISSUE THREAD

**Issue by petevine** [opensludge/opensludge#5]
Hi,

The gist of the problem on Odroid C1 is this happens to be the most problem-free colour depth at the moment. Here's a trace:

````
(gdb) run
Starting program: /home/odroid/sludge-engine -d 1 /usr/share/out-of-order/gamedata
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
EGL Opening X11 display
EGL Getting EGL display
[New Thread 0xb5d06450 (LWP 2190)]
EGL Initializing
[New Thread 0xb5506450 (LWP 2191)]
EGL_VENDOR: ARM
EGL_VERSION: 1.4 Linux-r5p0-01rel0
EGL_EXTENSIONS: EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_EXT_swap_buffers_with_damage EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_KHR_create_context 
*** Engine compiled Dec  9 2015 at 05:16:30.
Video mode 1024 768 set successfully.
EGL Found 3 available configs
EGL Config 0
EGL Binding API
EGL Creating Context
EGL Creating window surface
ERROR: EGL Error detected in file eglport/eglport.cpp at line 287: EGL_BAD_NATIVE_WINDOW (0x300B)
EGL ERROR: Unable to create EGL surface!
EGL ERROR: Unable to configure EGL. See previous error.
Compiling vertex shader... 

Compiling fragment shader... 

Shaders compiled. 
Shader program linked. 
[Thread 0xb5506450 (LWP 2191) exited]
EGL Closed

Program received signal SIGSEGV, Segmentation fault.
0xb675a862 in __GI___pthread_mutex_lock (mutex=0xb) at pthread_mutex_lock.c:66
66      pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  0xb675a862 in __GI___pthread_mutex_lock (mutex=0xb) at pthread_mutex_lock.c:66
#1  0xb6ba943c in XrmDestroyDatabase () from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#2  0xb6b99fe4 in _XFreeDisplayStructure () from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#3  0xb6b8f2bc in XCloseDisplay () from /usr/lib/arm-linux-gnueabihf/libX11.so.6
#4  0xb6f7060e in ?? () from /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0
````

One other GLES2 app I'd had a similar problem with, namely [caveexpress](https://github.com/mgerhardy/caveexpress), managed to make it work but it was using SDL2 however.

Thx

**Comment by tobihan** [comment]
Fixed in ffe411b7a573e5f29c608a90b6c78d8e50cadc7c
